language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
before_install:
  - npm install
after_success:
  # - npm test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/